### ISSUE TITLE
Doppins keeps comitting with my username

### ISSUE THREAD

**Issue by OptimusCrime** [doppins/doppins-docker#7]
Doppins is for some reason comitting using my user. I have no idea why this happens. As a result my activity feed is filled with stuff that is not my commits.

Is than a github issue or an issue with Doppins?

![skarmavbild 2016-08-05 kl 14 47 27](https://cloud.githubusercontent.com/assets/2326278/17437111/f6d08248-5b1b-11e6-913c-8d72f6c941f4.png)

**Comment by ekmartin** [comment]
We did this while @doppins-bot was blocked by GitHub (see https://github.com/doppins/doppins-docker/issues/6#issuecomment-236615845), which is the same as we do for private repositories. It should be back to normal now though, see https://github.com/dotKom/onlineweb4/pull/1610

Let me know if it still happens and I'll reopen :)

**Comment by OptimusCrime** [comment]
I have this on my front feed. Looks like it is still comitting as random members of the team? I just took this print screen.

<img width="655" alt="skarmavbild 2016-08-05 kl 21 14 18" src="https://cloud.githubusercontent.com/assets/2326278/17447950/c872a170-5b51-11e6-8481-896eccd720b9.png">

**Comment by ekmartin** [comment]
It's not committing as the user, but pushing as them - which has unfortunately always been the case. This is because it needs a user that has access to the repository, and picks one of the access tokens it has available when it's upgrading. Since @doppins-bot doesn't have any repository permissions, the only thing it can do is open pull requests (which everybody can do).

**Comment by sklirg** [comment]
Is it possible to lock this to a machine user, so that the machine user gets all the credit whilst us mortals are saved from unjust commits?
